<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <AssemblyName>FloatingDock</AssemblyName>
    <RootNamespace>FloatingDock</RootNamespace>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <NoWarn>$(NoWarn);CA1031;CA1303;CA1416;CA1515;CA1822;CA1852;CA2000;SA1009;SA1011;SA1116;SA1117;SA1200;SA1310;SA1402;SA1512;SA1513;SA1515;SA1600;SA1633</NoWarn>
  </PropertyGroup>
</Project>
